@USER_ID= 65f761c283304a607a5e1ac1

POST http://localhost:3000/users/{{USER_ID}}/picture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY3NjFjMjgzMzA0YTYwN2E1ZTFhYzEiLCJmdWxsbmFtZSI6eyJmaXJzdCI6InByb2plY3QiLCJsYXN0IjoiY29tcGxldGUifSwiZW1haWwiOiJwY0BnbWFpbC5jb20iLCJwcm9maWxlUGljdHVyZVBhdGgiOiJpbWFnZXMvZ3Vlc3QucG5nIiwiaWF0IjoxNzEwNzg3ODc2fQ.PrebDD80pscsPfi-NaUDI3-GdQVNkK8HX5MkWhyWPcc